CREATE TABLE USER (
  userID INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('Admin','Customer','Technician','Storekeeper') NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  lastLogin DATETIME NULL
);

SELECT * from user;

DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS USER (
  userID INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('Admin','Customer','Technician','Storekeeper') NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  lastLogin DATETIME NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
  CustomerID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  ContactNo VARCHAR(20),
  Address VARCHAR(255),
  DateRegistered DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES USER(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TECHNICIAN (
  TechnicianID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  ContactNo VARCHAR(20),
  Address VARCHAR(255),
  AvailabilityStatus ENUM('Available','Assigned','Inactive') DEFAULT 'Available',
  FOREIGN KEY (UserID) REFERENCES USER(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ADMIN (
  AdminID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  ContactNo VARCHAR(20),
  Address VARCHAR(255),
  FOREIGN KEY (UserID) REFERENCES USER(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS STOREKEEPER (
  StorekeeperID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  ContactNo VARCHAR(20),
  Address VARCHAR(255),
  FOREIGN KEY (UserID) REFERENCES USER(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKENS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    token VARCHAR(64) NOT NULL UNIQUE,
    expires_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USER(userID) ON DELETE CASCADE,
    INDEX idx_token (token),
    INDEX idx_user_id (user_id),
    INDEX idx_expires_at (expires_at)
);
